- name: stop and remove cysnet prover
  hosts: all
  tasks:
    - name: stop and remove prover docker container
      docker_container:
        state: absent
        name: "cysnet_prover"
        force_kill: true
      become: yes
