- name: run cysnet prover
  hosts: all
  tasks:
    - name: cysnet-prover
      docker_container:
        image: "10.234.1.250:5001/timemeansalot/cysnet_phase2:v2.6"
        device_requests:
          - # Add nVidia GPUs to this container
            driver: nvidia
            # device_ids:
            #   - "0"
            count: -1 # use all GPUs
            capabilities:
              - gpu
              - compute
              - utility
        name: "cysnet_prover"
        restart_policy: unless-stopped
        state: started
        # entrypoint: /bin/bash
        env:
          CHAIN_ID: "534352"
          REWARD_ADDRESS: "{{REWARD_ADDRESS}}"
          # LD_LIBRARY_PATH: "/prover:/usr/local/cuda/lib64"
          # RUST_LOG: "info"
          # REWARD_ADDRESS: "{{ lookup('file', '/root/cysic-prover/reward_address.txt') }}"
        volumes:
          - /home/cysic/.scroll_prover/v1/:/root/.scroll_prover:ro
          - /home/cysic/.scroll_prover/:/root/cysic-prover/params_assets/scroll
          - /home/cysic/:/root/cysic-prover/params_assets
        log_driver: syslog
        log_options:
          syslog-address: "udp://10.234.1.250:514"
      become: yes
